/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "9.0.0-beta16" apply true
}

dependencies {
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(project(":quickshop-bukkit"))
}

tasks {
    compileJava {
        sourceCompatibility = "21"
        targetCompatibility = "21"
    }

    jar {
        dependsOn(shadowJar)
        archiveFileName = "original-Addon-DisplayControl-${project.version}.jar"
    }

    shadowJar {
        archiveFileName = "QuickShop-Addon-DisplayControl-${project.version}.jar"
        archiveClassifier = ""

        configurations = listOf(project.configurations.shadow.get())
    }
}

group = "com.ghostchu.quickshop.addon"
description = "Addon-DisplayControl"
