/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.de.themoep.minedown.adventure)
    api(libs.com.ghostchu.thirdparty.jsonconfiguration)
    api(libs.net.minidev.json.smart)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.io.vavr.vavr)
    compileOnly(libs.org.maxgamer.quickshop)
    compileOnly(project(":quickshop-bukkit"))
}

group = "com.ghostchu.quickshop.addon"
description = "Addon-Reremake-Migrator"
