/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "9.0.0-beta16" apply true
}

dependencies {
    api(libs.de.themoep.minedown.adventure)
    api(libs.com.ghostchu.thirdparty.jsonconfiguration)
    api(libs.net.minidev.json.smart)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.io.vavr.vavr)
    compileOnly(libs.org.maxgamer.quickshop) {
        isTransitive = false
    }
    compileOnly(project(":quickshop-bukkit"))
}

tasks {
    compileJava {
        sourceCompatibility = "21"
        targetCompatibility = "21"
    }

    jar {
        dependsOn(shadowJar)
        archiveFileName = "original-Addon-ReRemake-Migrator-${project.version}.jar"
    }

    shadowJar {
        archiveFileName = "QuickShop-Addon-ReRemake-Migrator-${project.version}.jar"
        archiveClassifier = ""

        configurations = listOf(project.configurations.shadow.get())
    }
}

group = "com.ghostchu.quickshop.addon"
description = "Addon-Reremake-Migrator"
