/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":quickshop-platform-interface"))
    compileOnly(libs.io.papermc.paper.paper.api.x1)
}

description = "quickshop-platform-paper"
