/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(libs.com.velocitypowered.velocity.api)
    compileOnly(libs.com.velocitypowered.velocity.api)
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-Velocity"
