/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "9.0.0-beta16" apply true
}

dependencies {
    compileOnly(libs.com.velocitypowered.velocity.api)
    compileOnly(libs.com.velocitypowered.velocity.api)
}

tasks {
    compileJava {
        sourceCompatibility = "21"
        targetCompatibility = "21"
    }

    jar {
        dependsOn(shadowJar)
        archiveFileName = "original-${description}-${project.version}.jar"
    }

    shadowJar {
        archiveFileName = "QuickShop-${description}-${project.version}.jar"
        archiveClassifier = ""

        configurations = listOf(project.configurations.shadow.get())
    }
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-Velocity"
