/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":common"))
    api(libs.com.dre.brewery.breweryx)
    api(libs.com.github.slimefun.slimefun4)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.nexomc.nexo)
    compileOnly(libs.io.th0rgal.oraxen)
    compileOnly(libs.xyz.xenondevs.nova.nova.api)
    compileOnly(project(":quickshop-bukkit"))
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-MatcherPlus"
