name: qsaddon-${project.artifactId}
version: '${project.version}'
main: com.ghostchu.quickshop.addon.${project.artifactId}.Main
api-version: '1.20'
depend:
  - QuickShop-Hikari
authors: [ Ghost_chu ]
permissions:
  quickshopaddon.list.self:
    description: Allow player to use /quickshop list to query self
    default: true
  quickshopaddon.list.other:
    description: Allow player to use /quickshop list <player> to query other
    default: op