name: qsaddon-${project.artifactId}
version: '${project.version}'
main: com.ghostchu.quickshop.addon.${project.artifactId}.Main
api-version: '1.20'
depend:
  - QuickShop-Hikari
  - DiscordSRV
authors: [ Ghost_chu ]
#libraries:
#  - net.dv8tion:JDA:4.4.0_352.fix-2
permissions:
  quickshopaddon.discord.use:
    description: Allows players to use discord commands
    default: true