name: QuickShop-Hikari
main: com.ghostchu.quickshop.QuickShopBukkit
#Has to be included for folia support
folia-supported: true
softdepend:
  - Vault
  - Reserve
  - PlaceholderAPI
  - LuckPerms
  - PermissionEx
  - GroupManager
  - Essentials
  - CMI
  - ProtocolLib
  - NBTAPI
  - NBT-API
  - ItemNBTAPI
  - Mohist
  - EcoEnchants # Add ecoenchants to allow us to detect if ee is installed for compatibility warning
  - CoinsEngine
  - Treasury
  - BetterEconomy # Depends on Treasury
  - TheNewEconomy
api-version: 1.18
# TODO: https://github.com/PaperMC/Paper/pull/7177
#libraries:
#  - org.apache.commons:commons-compress:1.25.0
#  - org.apache.commons:commons-lang3:3.14.0
#  - org.apache.commons:commons-text:1.11.0
#  - com.rollbar:rollbar-java:1.9.0
#  - commons-codec:commons-codec:1.15
#  - cc.carm.lib:easysql-hikaricp:0.4.7
#  - com.h2database:h2:2.1.214
#  - com.ghostchu:simplereloadlib:1.1.2
#  - com.konghq:unirest-java:3.14.5
#  - com.github.juliomarcopineda:jdbc-stream:0.1.1
#  - one.util:streamex:0.8.2
#  - commons-lang:commons-lang:2.6
#  - net.sourceforge.csvjdbc:csvjdbc:1.0.41
#  - org.dom4j:dom4j:2.1.4
#  - org.slf4j:slf4j-jdk14:2.0.10
#  - com.vdurmont:semver4j:3.1.0
#  - com.ghostchu.crowdin:crowdinota:1.0.3
#  - com.google.code.gson:gson:2.10.1
#  - net.kyori:adventure-api:4.15.0
#  - net.kyori:adventure-key:4.15.0
#  - net.kyori:adventure-nbt:4.15.0
#  - net.kyori:adventure-platform-api:4.3.2
#  - net.kyori:adventure-platform-bukkit:4.3.2
#  - net.kyori:adventure-platform-facet:4.3.2
#  - net.kyori:adventure-platform-viaversion:4.3.2
#  - net.kyori:adventure-serializer-configurate4:4.15.0
#  - net.kyori:adventure-text-logger-slf4j:4.15.0
#  - net.kyori:adventure-text-minimessage:4.15.0
#  - net.kyori:adventure-text-serializer-ansi:4.15.0
#  - net.kyori:adventure-text-serializer-bungeecord:4.3.2
#  - net.kyori:adventure-text-serializer-gson-legacy-impl:4.15.0
#  - net.kyori:adventure-text-serializer-json:4.15.0
#  - net.kyori:adventure-text-serializer-json-legacy-impl:4.15.0
#  - net.kyori:adventure-text-serializer-legacy:4.15.0
#  - net.kyori:adventure-text-serializer-plain:4.15.0
#  - net.kyori:examination-api:1.3.0
#  - net.kyori:examination-string:1.3.0
authors:
  - Ghost_chu
  - PotatoCraft Studio
  - Netherfoam
  - Timtower
  - KaiNoMood (KaiKikuchi)
  - sandtechnology
  - jho5245
  - cakoyo
  - Andre601
  - Ectabro
  - Chris6ix
  - portlek
  - log4b0at
  - deadman96385
  - tiararinne
  - DoctaEnkoda
  - CarmJos
  - YuanYuanOwO
  - Mgazul
  - mart-r
  - Tim269
  - raphtaliapt
  - creatorfromhell
  - LoneDev6
  - Steven-OS
  - confuxeon
  - ibmibmibm
  - judgetread
  - mfnalex
  - Warriorrrr
  - PyvesB
  - yannicklamprecht
  - ORelio
  - RMSCA
  - Starmism
  - yiwenwang2090
  - PaulBGD
  - Nlkomaru
  - harry0198
  - Draesia
  - Localized community members on Crowdin
description: QuickShop is a shop plugin that allows players to easily sell/buy any items from a chest without any commands. In fact, none of the commands that QuickShop provides are ever needed by a player.

version: ${project.version}

permissions:
  quickshop.player:
    description: The permission that provide all player need have permissions
    default: op
    children:
      quickshop.use: true
      quickshop.create.sell: true
      quickshop.create.buy: true
      quickshop.create.stacks: true
      quickshop.create.changeitem: true
      quickshop.create.changeamount: true
      quickshop.create.changeprice: true
      quickshop.create.double: true
      quickshop.create.cmd: true
      quickshop.transferall: true
      quickshop.transferownership: true
      quickshop.find: true
      quickshop.fetchmessage: true
      quickshop.staff: true
      quickshop.staffall: true
      quickshop.preview: true
      quickshop.currency: true
      quickshop.toggledisplay: true
      quickshop.shopnaming: true
      quickshop.permission: true
      quickshop.benefit: true
      quickshop.browse: true
      quickshop.sign: true
      #quickshop.history: true
      #quickshop.history.owned: true
      #quickshop.history.accessible: true
      quickshop.suggestprice: true
  quickshop.moderator:
    description: The permission that provide all moderator need have permissions
    default: op
    children:
      quickshop.setowner: true
      quickshop.other.destroy: true
      quickshop.other.open: true
      quickshop.other.price: true
      quickshop.bypass.*: true
      quickshop.alerts: true
      quickshop.create.admin: true
      quickshop.history.*: true
      quickshop.transferownershop.other: true
      quickshop.other.changeitem: true
      quickshop.other.changeamount: true
      quickshop.other.staff: true
      quickshop.other.currency: true
      quickshop.other.taxaccount: true
      quickshop.other.toggledisplay: true
      quickshop.purge: true
      quickshop.other.setowner: true
      quickshop.taxaccount: true
      quickshop.other.shopnaming: true
      quickshop.bypass.namefee: true
      quickshop.other.search: true
      quickshop.other.preview: true
      quickshop.other.use: true
      quickshop.other.benefit: true
      quickshop.other.sign: true
      quickshop.other.history: true
  quickshop.create.sell:
    description: Allows a player to sell from a shop.
    default: op
  quickshop.create.buy:
    description: Allows a player to buy from a shop.
    default: op
  quickshop.create.double:
    description: Allows a player to create a double shop.
    default: op
  quickshop.create.changeprice:
    description: Allows a player to change their shop's price.
    default: op
  quickshop.create.cmd:
    description: Allows a player to use /quickshop create to create a shop.
    default: op
  quickshop.create.admin:
    description: Allows a player use /quickshop supercreate to create a shop that bypasses all protection checks.
    default: op
  quickshop.create.changeitem:
    description: Allows a player to change their shop's item.
    default: op
  quickshop.create.changeamount:
    description: Allows a player to change their shop's item amount per trade.
    default: op
  quickshop.create.stacks:
    description: Allows a player to create a shop with stacked items.
    default: op
  quickshop.use:
    description: Allows a player to buy/sell using other player's shops.
    default: true
  quickshop.unlimited:
    description: Allows a staff member to use /quickshop unlimited to make a shop infinite.
    default: op
  quickshop.bypass.<itemID>:
    description: Allows a player to sell blacklisted <itemIDs>.
    default: op
  quickshop.other.destroy:
    description: Allows a staff member to destroy other player's shops even if they are locked.
    default: op
  quickshop.other.open:
    description: Allows a staff member to open someone else's shop even if it is locked.
    default: op
  quickshop.other.price:
    description: Allows a staff member to change the price of someone else's shop.
    default: op
  quickshop.other.item:
    description: Allows a staff member to change the item of someone else's shop.
    default: op
  quickshop.other.amount:
    description: Allows a staff member to change the item amount per trade of someone else's shop.
    default: op
  quickshop.other.sign:
    description: Allows a staff member to change the sign type of someone else's shop.
    default: op
  quickshop.setowner:
    description: Allows a staff member to change the owner of any shop.
    default: op
  quickshop.staff:
    description: Allows a shop owner to manage their shop staff.
    default: op
  quickshop.staffall:
    description: Allows a shop owner to manage their shop staff for all shops.
    default: op
  quickshop.other.staff:
    description: Allows a other player force editing the shop staffs.
    default: op
  quickshop.find:
    description: Allows a player to locate the nearest shop that has a specific item type. Distance configurable in config.
    default: true
  quickshop.refill:
    description: Allows a staff member to refill the shop they're looking at with the given number of items.
    default: op
  quickshop.empty:
    description: Allows a staff member to empty the shop they're looking at of all items.
    default: op
  quickshop.debug:
    description: Enables developer mode.
    default: op
  quickshop.export:
    description: Allows exporting the database to a plain file.
    default: op
  quickshop.alerts:
    description: Recieve cheat alerts, plugin warnings and update notifications.
    default: op
  quickshop.about:
    description: Show QuickShop's about message.
    default: true
  quickshop.info:
    description: Show QuickShop's Statistics.
    default: op
  quickshop.fetchmessage:
    description: Allows the use of the /quickshop fetchmessage command to manually fetch shop messages from the database. Will not effect auto fetch if turned on...
    default: true
  quickshop.paste:
    description: Allows the use of the /quickshop paste command to upload server information to Pastebin. !WARNING! This will upload your data and may leak your server configuration and other sensitive information.
    default: op
  quickshop.preview:
    description: Permission to preview item using a GUI.
    default: true
  quickshop.tax:
    description: Permission to bypass taxes.
    default: op
  quickshop.tax.bypassunlimited:
    description: Permission to bypass taxes but for unlimited shops ONLY.
    default: op
  quickshop.cleanghost:
    description: Permission to use /quickshop cleanghost.
    default: op
  quickshop.reset:
    description: Permission to use /quickshop reset.
    default: op
  quickshop.bypasscreatefee:
    description: Permission to bypass the creation fee.
    default: op
  quickshop.recovery:
    description: Permission to use /quickshop recovery. !WARNING! DO NOT EXECUTE THIS COMMAND IF YOU DON'T KNOW WHAT YOU'RE DOING.
    default: op
  quickshop.removeall.other:
    description: Permission to use /quickshop removeall <player> to remove other player's shops.
    default: op
  quickshop.removeall.self:
    description: Permission to use /quickshop removeall to remove player's own shops.
    default: op
  quickshop.removeworld:
    description: Permission to use /quickshop removeworld.
    default: op
  quickshop.currency:
    description: Permission to use /quickshop currency.
    default: op
  quickshop.other.currency:
    description: Permission to use /quickshop currency but for other's shops.
    default: op
  quickshop.showdisabled:
    description: Permission to see disabled commands in help list.
    default: op
  quickshop.taxaccount:
    description: Permission to use /quickshop taxaccount
    default: op
  quickshop.other.taxaccount:
    description: Permission to use /quickshop taxaccount on others shops
    default: op
  quickshop.toggledisplay:
    description: Permission to use /quickshop toggledisplay
    default: op
  quickshop.other.toggledisplay:
    description: Permission to use /quickshop toggledisplay on others shops
    default: op
  quickshop.purge:
    description: Permission to use /quickshop purge
    default: op
  quickshop.shopnaming:
    description: Permission to use /quickshop name
    default: op
  quickshop.other.shopnaming:
    description: Permission to use /quickshop name on others shops
    default: op
  quickshop.bypass.namefee:
    description: Permission to use /quickshop name without the fee
    default: op
  quickshop.permission:
    description: Permission to use /quickshop permission
    default: op
  quickshop.other.search:
    description: Permission to bypass the search flag restriction
    default: op
  quickshop.other.preview:
    description: Permission to bypass the shop preview restriction
    default: op
  quickshop.other.use:
    description: Permission to bypass the purchase restriction
    default: op
  quickshop.database:
    description: Permission to use /quickshop database
    default: op
  quickshop.benefit:
    description: Permission to use /quickshop benefit
    default: op
  quickshop.other.benefit:
    description: Permission to bypass the benefit permission check
    default: op
  quickshop.browse:
    description: Permission to use /quickshop browse
    default: op
  quickshop.transferall:
    description: Permission to transfer all shops of a player to someone
    default: op
  quickshop.transferall.other:
    description: Permission to transfer others all shops of a player to someone
    default: op
  quickshop.transferownership:
    description: Permission to transfer a single shop of a player to someone
    default: op
  quickshop.transferownership.other:
    description: Permission to transfer a single shop of a player to someone without permission check
    default: op
  quickshop.sign:
    description: Permission to change the shop sign type
    default: op
  quickshop.history:
    description: Permission to view the shop history
    default: op
  quickshop.history.owned:
    description: Permission to view the shop history which owned
    default: op
  quickshop.history.accessible:
    description: Permission to view the shop history which the store granted player VIEW_PURCHASE_LOGS permission
    default: op
  quickshop.history.global:
    description: Permission to view the shop history on this server
    default: op
  quickshop.other.history:
    description: Permission to view the other's shop history
    default: op
  quickshop.suggestprice:
    description: Suggest the shop recommend price
    default: op