[versions]
slf4jApi = "2.0.17"
slf4jSimple = "2.0.17"
paperApi = "1.21-R0.1-SNAPSHOT"
paperApiPinned = "1.21.4-R0.1-SNAPSHOT"
shadow = "9.6.1"
versionsPlugin = "0.51.0"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paperApi" }
paper-api-pinned = { module = "io.papermc.paper:paper-api", version.ref = "paperApiPinned" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
