[versions]
lombok = "1.18.46"
jetbrainsAnnotations = "26.0.2-1"
slf4jApi = "2.0.17"
slf4jSimple = "2.0.17"
paperApi = "1.21-R0.1-SNAPSHOT"
paperApiPinned = "1.21.4-R0.1-SNAPSHOT"
paperlib = "1.0.8"
shadow = "9.6.1"
versionsPlugin = "0.51.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paperApi" }
paper-api-pinned = { module = "io.papermc.paper:paper-api", version.ref = "paperApiPinned" }
paperlib = { module = "io.papermc:paperlib", version.ref = "paperlib" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
