name: 'Bug Report'
description: 'Report a bug with QuickShop to us.'

title: '[BUG] '
labels:
  - 'Bug'

body:
  - type: 'markdown'
    attributes:
      value: |-
        ## Please Read!
        This Form is reserved for **Bug reports only!**

        - For performance issues with QuickShop, open a [Performance Report](https://github.com/Quickshop-Community/QuickShop-Hikari/issues/new?template=performance.yml&labels=performance).
        - For contributions towards the wiki, open a [Wiki Contribution](https://github.com/Quickshop-Community/QuickShop-Hikari/issues/new?template=wiki_contribution.yml.yml&labels=wiki).
        - Feature requests or other suggestions should be made in the [Discussions](https://github.com/Quickshop-Community/QuickShop-Hikari/discussions).

        Please fill out all required fields in their entirety and as detailed as possible. Failing to do so could get your issue closed without any warning.
  - type: 'textarea'
    attributes:
      label: 'Description'
      description: |-
        Describe the bug as detailed as possible.
        You cann upload screenshots of the bug in the "screenshots" section further down.
      placeholder: 'When I used Quickshop did ... happen.'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Steps to reproduce'
      description: 'List your steps on how to reproduce this bug reliably here.'
      placeholder: |-
        1. Do something
        2. ...
        3. Bug!
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Expected Behaviour'
      description: 'What did you expect QuickShop to do?'
      placeholder: 'QuickShop should ...'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Screenshots'
      description: |-
        Provide screenshots to show the bug, if possible.
        Gifs or Videos are also welcome if they can help explaining the issue.
      placeholder: 'When I used Quickshop did ... happen.'
    validations:
      required: false
  - type: 'input'
    attributes:
      label: '`/quickshop paste` URL'
      description: |-
        Please execute `/quickshop paste` in-game or `quickshop paste` in your server console.
        The plugin will generate a URL that you can then post in the field below.

        If you can't create a paste, should you upload other files such as the `latest.log` file to https://paste.helpch.at and share the URL.

        If QuickShop is unable to generate a Paste will it create a file under `plugins/QuickShop-Hikari/`
      placeholder: 'https://paste.helpch.at/...'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Additional Context'
      description: 'Feel free to include any info that may not fit any of the previous sections.'
      placeholder: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam ...'
  - type: checkboxes
    id: check-list
    attributes:
      label: Checklist
      description: Check all inspections according to the checklist below.
      options:
        - label: "I'm running Paper or Spigot, and not a fork"
          required: false
        - label: I confirm that Paper/Spigot has been updated to the latest build
          required: false
        - label: I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
          required: false
        - label: I confirm that I have not read these checkboxes and therefore I just ticked them all.
          required: false
        - label: "I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here."
          required: false
        - label: "I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior."
          required: false
        - label: "I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason."
          required: false
