name: 'Performance Report'
description: 'Report performance issues with QuickShop.'

title: '[PERFORMANCE] '
labels:
  - 'Performance Issue'

body:
  - type: 'markdown'
    attributes:
      value: |-
        ## Please Read!
        This Form is reserved for **Performance reports only!**

        - For Bugs or issues with QuickShop, open a [Bug Report](https://github.com/Ghost-chu/QuickShop-Hikari/issues/new?template=bug_report.yml&labels=bug).
        - For contributions towards the wiki, open a [Wiki Contribution](https://github.com/Ghost-chu/QuickShop-Hikari/issues/new?template=wiki_contribution.yml.yml&labels=wiki).
        - Feature requests or other suggestions should be made in the [Discussions](https://github.com/Ghost-chu/QuickShop-Hikari/discussions).

        Please fill out all required fields in their entirety and as details as possible. Failing to do so could get your issue closed without any warning.

        #### Additional Notes
        Please only provide Sampler results from [Spark](https://www.spigotmc.org/resources/57242/)! Spigot Timings - no matter if v1 or v2 - will be ignored.
        Your issue will be closed without any reply if only a Spigot Timings Report was provided.
  - type: 'textarea'
    attributes:
      label: 'Description'
      description: |-
        Describe the issue as detailed as possible.
        You cann upload screenshots of the issue in the "screenshots" section further down.
      placeholder: 'When I used Quickshop did ... happen.'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Steps to reproduce'
      description: 'List your steps on how to reproduce this issue reliably here.'
      placeholder: |-
        1. Do something
        2. ...
        3. Bad performance!
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Expected Behaviour'
      description: 'What did you expect QuickShop to do?'
      placeholder: 'QuickShop should ...'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Screenshots'
      description: |-
        Provide screenshots to show the performance problems, if possible.
        Gifs or Videos are also welcome if they can help explaining the issue.
      placeholder: 'When I used Quickshop did ... happen.'
    validations:
      required: true
  - type: 'input'
    attributes:
      label: '`/quickshop paste` URL'
      description: |-
        Please execute `/quickshop paste` in-game or `qs paste` in your server console.
        The plugin will generate a URL that you can then post in the field below.

        If you can't create a paste, should you upload other files such as the `latest.log` file to https://paste.helpch.at and share the URL.

        If QuickShop is unable to generate a Paste will it create a file under `plugins/QuickShop-Hikari/`
      placeholder: 'https://paste.helpch.at/...'
    validations:
      required: true
  - type: 'input'
    attributes:
      label: 'Spark Sample URL'
      description: |-
        **How to use [Spark](https://www.spigotmc.org/resources/57242/)**

        1. Download the plugin from the Spigot page (linked above) if you haven't already.
        2. Add it to the server like any other plugin (Stop Server, add jar, start server).
        3. Join the server and execute `/spark sampler --start`
        4. Wait at least 10 minutes and/or perform the actions that cause performance issues with QuickShop.
        5. Execute `/spark sampler --stop` to get the URL
        6. Paste the URL in the field below.
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Additional Context'
      description: 'Feel free to include any info that may not fit any of the previous sections.'
      placeholder: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam ...'
