name: 'Wiki Contribution'
description: 'Inform about a Contribution that you want to make towards the wiki.'

title: '[WIKI] '
labels:
  - 'Wiki'

body:
  - type: 'markdown'
    attributes:
      value: |-
        ## Please Read!
        This Form is reserved for **Wiki Contributions only!**

        - For Bugs or issues with QuickShop, open a [Bug Report](https://github.com/Quickshop-Community/QuickShop-Hikari/issues/new?template=bug_report.yml&labels=bug).
        - For performance issues with QuickShop, open a [Performance Report](https://github.com/Quickshop-Community/QuickShop-Hikari/issues/new?template=performance.yml&labels=performance).
        - Feature requests or other suggestions should be made in the [Discussions](https://github.com/Quickshop-Community/QuickShop-Hikari/discussions).

        Please fill out all required fields in their entirety and as detailed as possible. Failing to do so could get your issue closed without any warning.
  - type: 'input'
    attributes:
      label: 'Repository URL'
      description: 'Provide a URL to your GitHub Repository containing your Wiki changes.'
      placeholder: 'https://github.com/example/repo'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Changes'
      description: 'Provide a list of all changes you made.'
      placeholder: |-
        - Changed this.
        - Changed that.
        - Also changed this!
    validations:
      required: true
