/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(project(":quickshop-bukkit"))
}

group = "com.ghostchu.quickshop.compatibility"
description = "quickshop-compatibility-common"
