/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.github.juliomarcopineda.jdbc.stream)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.github.plan.player.analytics.plan)
    compileOnly(libs.cc.carm.lib.easysql.api)
    compileOnly(project(":quickshop-bukkit"))
}

group = "com.ghostchu.quickshop.addon"
description = "Addon-Plan"
