name: qscompat-${project.artifactId}
version: '${project.version}'
main: com.ghostchu.quickshop.compatibility.${project.artifactId}.Main
#Has to be included for folia support
folia-supported: true
api-version: '1.20'
depend:
  - AdvancedRegionMarket
  - QuickShop-Hikari
authors: [ Ghost_chu ]
description: Compatibility module for AdvancedRegionMarket
permissions:
  quickshop.arm.admin:
    description: Allows a player to bypass the AdvancedRegionMarket region check when admin-override is enabled.
    default: op
