name: qscompat-advanvedregionmarket
version: '${project.version}'
main: com.ghostchu.quickshop.compatibility.advancedregionmarket.Main
api-version: 1.16
depend:
  - AdvancedRegionMarket
  - QuickShop-Hikari
authors: [ Ghost_chu ]
