/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":common"))
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.georgev22.voidchest.shade.voidchestapi.shade)
    compileOnly(project(":quickshop-bukkit"))
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-VoidChest"
