/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":common"))
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit)
    compileOnly(project(":quickshop-bukkit"))
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-WorldEdit"
