/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":common"))
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(project(":quickshop-bukkit"))
    compileOnly(files("lib/CMILib1.5.4.1.jar"))
    compileOnly(files("lib/Residence5.1.7.3.jar"))
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-Residence"
