/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-releases/")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-snapshots/")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://repo.essentialsx.net/releases/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://repo.tcoded.com/releases")
    }

    maven {
        url = uri("https://www.jitpack.io")
    }

    maven {
        url = uri("https://maven.mohistmc.com/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.bluecolored.de/releases")
    }

    maven {
        url = uri("https://m2.dv8tion.net/releases")
    }

    maven {
        url = uri("https://nexus.scarsz.me/content/groups/public/")
    }

    maven {
        url = uri("https://repo.mikeprimm.com/")
    }

    maven {
        url = uri("https://repo.minebench.de/")
    }

    maven {
        url = uri("https://nexus.alex9849.net/repository/maven-releases/")
    }

    maven {
        url = uri("https://nexus.alex9849.net/repository/maven-snapshots/")
    }

    maven {
        url = uri("https://repo.jeff-media.com/public/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-snapshots")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://repo.opencollab.dev/main")
    }

    maven {
        url = uri("https://repo.opencollab.dev/maven-snapshots")
    }

    maven {
        url = uri("https://repo.auxilor.io/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.magmaguy.com/releases")
    }

    maven {
        url = uri("https://repo.songoda.com/repository/minecraft-plugins/")
    }

    maven {
        url = uri("https://repo.william278.net/releases")
    }

    maven {
        url = uri("https://nexus.iridiumdevelopment.net/repository/maven-releases/")
    }

    maven {
        url = uri("https://maven.devs.beer/")
    }

    maven {
        url = uri("https://repo.nexomc.com/releases")
    }

    maven {
        url = uri("https://repo.oraxen.com/releases")
    }

    maven {
        url = uri("https://repo.xenondevs.xyz/releases")
    }

    maven {
        url = uri("https://repo.jsinco.dev/releases")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://repo.bg-software.com/repository/api/")
    }

    maven {
        url = uri("https://repo.glaremasters.me/repository/towny/")
    }

    maven {
        url = uri("https://repo.georgev22.com/releases")
    }
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.38")
    compileOnly("org.jetbrains:annotations:26.0.2")
}

group = "com.ghostchu"
version = "6.2.0.11-SNAPSHOT-4"
