/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(libs.net.md.v5.bungeecord.api)
    compileOnly(libs.net.md.v5.bungeecord.api)
    compileOnly(libs.org.geysermc.geyser.api)
    compileOnly(libs.org.geysermc.floodgate.api)
}

group = "com.ghostchu.quickshop.compatibility"
description = "Compat-BungeeCord-Geyser"
