#Should we prevent the creation of a shop or trade with a shop outside claim's area?
whitelist-mode: false
#Should we delete the shop in a claim when the shop owner loses the permission for this land?
delete-on-lose-permission: false
#Delete all shops in the claim when that claim was deleted
delete-shops-in-claim-when-deleted: false
#Delete all shops in a claim's chunk when that chunk is unclaimed
delete-shops-in-chunk-when-unclaimed: false