<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ghostchu</groupId>
        <artifactId>quickshop-hikari</artifactId>
        <version>6.3.0.0-SNAPSHOT-6</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <groupId>com.ghostchu.quickshop.compatibility</groupId>
    <artifactId>betonquest</artifactId>
    <packaging>takari-jar</packaging>

    <name>Addon-BetonQuest</name>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>betonquest-repo</id>
            <url>https://nexus.betonquest.org/repository/betonquest/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>${depend.paper}</version>
        </dependency>
        <dependency>
            <groupId>com.ghostchu.quickshop.compatibility</groupId>
            <artifactId>common</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.ghostchu</groupId>
            <artifactId>quickshop-bukkit</artifactId>
            <version>${project.parent.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.betonquest</groupId>
            <artifactId>betonquest</artifactId>
            <version>${addon.betonquest}</version>
            <scope>provided</scope>
            <exclusions>
                <!-- BetonQuest depends are a real bitch -->
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>
