name: qsaddon-${project.artifactId}
version: '${project.version}'
main: com.ghostchu.quickshop.addon.${project.artifactId}.Main
#Has to be included for folia support
folia-supported: true
api-version: '1.20'
depend:
  - BlueMap
authors: [ Ghost_chu ]
