/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":quickshop-common"))
    compileOnly(libs.io.papermc.paper.paper.api)
}

description = "quickshop-api"
